import { Layout } from "@/components/layout/Layout";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

export default function TermsPage() {
  return (
    <Layout>
      <section className="section-padding bg-secondary"><div className="container-premium"><div className="max-w-3xl mx-auto text-center"><h1 className="heading-display text-foreground mb-6">Termos e Disclaimers</h1><p className="text-body text-lg">Informações importantes sobre nossos serviços, expectativas e limitações.</p></div></div></section>
      <section className="section-padding bg-background">
        <div className="container-premium"><div className="max-w-3xl mx-auto">
          <div className="card-premium p-8 md:p-12 space-y-12">
            <div><h2 className="heading-card text-foreground mb-4">Disclaimer de Resultados</h2><div className="text-body space-y-4"><p>A UNV fornece serviços de direção comercial, treinamento e cobrança. <strong>Resultados não são garantidos.</strong> Quaisquer referências a "quick wins", "payback" ou melhorias de receita são projeções operacionais baseadas em melhoria de execução—não promessas de resultados específicos.</p><p>Resultados reais dependem de múltiplos fatores incluindo:</p><ul className="list-disc list-inside space-y-2 text-muted-foreground"><li>Qualidade e consistência da execução do time</li><li>Condições de mercado e cenário competitivo</li><li>Qualidade e volume de leads</li><li>Fit de produto/serviço com o mercado</li><li>Comprometimento do cliente com o processo</li><li>Fatores econômicos externos</li></ul></div></div>
            <div><h2 className="heading-card text-foreground mb-4">Escopo do Serviço</h2><div className="text-body space-y-4"><p>A UNV atua como Diretor Comercial externo. Fornecemos:</p><ul className="list-disc list-inside space-y-2 text-muted-foreground"><li>Direção estratégica e definição de prioridades</li><li>Treinamento prático em processos e scripts de vendas</li><li>Monitoria contínua e cobrança</li><li>Frameworks, templates e ferramentas de suporte</li></ul><p className="font-medium">A UNV NÃO:</p><ul className="list-disc list-inside space-y-2 text-muted-foreground"><li>Faz vendas ou fecha negócios em nome dos clientes</li><li>Gerencia sistemas CRM ou bancos de dados do cliente</li><li>Fornece tráfego pago ou serviços de marketing</li><li>Garante resultados específicos de receita</li><li>Substitui a responsabilidade do cliente pela execução</li></ul></div></div>
            <div><h2 className="heading-card text-foreground mb-4">Esclarecimento sobre Projeção de Payback</h2><div className="text-body space-y-4"><p>Referências a "payback até o mês 3" ou prazos similares são <strong>projeções operacionais</strong>, não garantias. Essas projeções assumem:</p><ul className="list-disc list-inside space-y-2 text-muted-foreground"><li>Implementação completa dos processos recomendados</li><li>Execução consistente pelo time dos métodos treinados</li><li>Fluxo adequado de leads para trabalhar</li><li>Disponibilidade do cliente para sessões agendadas</li><li>Ausência de disrupções externas significativas</li></ul></div></div>
            <div><h2 className="heading-card text-foreground mb-4">Termos da Experiência Mansão</h2><div className="text-body space-y-4"><p>A Experiência Mansão é um benefício exclusivo disponível para membros UNV Partners sob as seguintes condições:</p><ul className="list-disc list-inside space-y-2 text-muted-foreground"><li>Limitado a 5 convidados por mês</li><li>Entrada por convite e curadoria—não garantida com membership</li><li><strong>Todos os custos (viagem, hospedagem, alimentação, atividades) são responsabilidade do cliente</strong></li><li>UNV reserva o direito de aceitar ou recusar participação</li><li>Participantes devem cumprir diretrizes de conduta</li><li>Datas e locais são determinados pela UNV e podem mudar</li></ul></div></div>
            <div><h2 className="heading-card text-foreground mb-4">Política de Cancelamento e Reembolso</h2><div className="text-body space-y-4"><p>Políticas variam por tipo de produto:</p><ul className="list-disc list-inside space-y-2 text-muted-foreground"><li><strong>Implementações únicas</strong> (Core, Growth Room): Não reembolsáveis após início do trabalho</li><li><strong>Assinaturas recorrentes</strong> (Control, Partners, Sales Ops): Cancelamento com aviso de 30 dias; reembolsos proporcionais não fornecidos</li><li><strong>Programas anuais</strong> (Sales Acceleration): Sujeitos a termos específicos de compromisso no contrato assinado</li></ul></div></div>
          </div>
          <div className="text-center mt-12"><p className="text-small mb-6">Última atualização: Dezembro 2024</p><Link to="/apply"><Button variant="premium" size="lg">Aplicar para Diagnóstico</Button></Link></div>
        </div></div>
      </section>
    </Layout>
  );
}
