ALTER TABLE public.crm_leads
  ADD COLUMN IF NOT EXISTS fbclid text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ad_name text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS adset_name text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS campaign_name text DEFAULT NULL;